"""Prompt templates for Claude API interactions."""

import json
import re
from typing import List, Dict, Any


def extract_json(text: str) -> Any:
    """
    Extract JSON from text that might be wrapped in markdown code blocks.

    Handles:
    - Raw JSON
    - ```json ... ```
    - ``` ... ```
    - JSON with surrounding text

    Returns the parsed JSON object/array.
    """
    text = text.strip()

    # Try to extract from markdown code blocks
    # Match ```json ... ``` or ``` ... ```
    code_block_match = re.search(r'```(?:json)?\s*([\s\S]*?)```', text)
    if code_block_match:
        json_str = code_block_match.group(1).strip()
        return json.loads(json_str)

    # If no code block, try to find JSON object/array
    # Look for { ... } or [ ... ]
    json_match = re.search(r'(\{[\s\S]*\}|\[[\s\S]*\])', text)
    if json_match:
        json_str = json_match.group(1).strip()
        return json.loads(json_str)

    # Try parsing as-is
    return json.loads(text)


# =============================================================================
# CORE PROSE PHILOSOPHY
# =============================================================================
# This is the foundational guidance for all prose generation. The project's
# style guide can extend or override these rules, but this baseline ensures
# human-quality prose even without a custom style guide.
# =============================================================================

PROSE_PHILOSOPHY = """
## CRITICAL: Human-Quality Prose Standards

Your prose must read as if written by a skilled human author, not generated by AI.
This is non-negotiable. Readers should never suspect AI involvement.

### Banned Vocabulary
Never use these words - they are AI tells that immediately mark prose as machine-generated:
- delve, delved, delving
- tapestry (when used metaphorically)
- myriad
- whilst, amidst, amongst
- commence, utilise/utilize
- plethora
- multifaceted
- paradigm
- synergy
- leverage (as a verb)
- facilitate
- encompass
- furthermore, moreover, additionally (as sentence starters)
- "It's important to note that..."
- "In terms of..."

### Patterns to Avoid
- **Balanced sentence structures**: Don't write everything in threes or perfect parallels
- **Purple prose**: Avoid overwrought, flowery descriptions. Precision beats decoration.
- **Adverb overuse**: Strong verbs don't need propping up with adverbs
- **Filter words**: Avoid "he felt", "she noticed", "he realized" - just show the thing
- **Hedging language**: No "somewhat", "rather", "quite", "slightly" unless voice-appropriate
- **Overly formal constructions**: Write how published novelists write, not how essays read
- **Everything resolving neatly**: Real scenes have rough edges, unfinished thoughts, interruptions

### Voice Authenticity
- Vary sentence length dramatically - some very short, some long and winding
- Use fragments when they work
- Let characters interrupt each other, trail off, speak imperfectly
- Embrace specific, concrete details over abstract descriptions
- Trust the reader - don't over-explain emotions or motivations
- Write with confidence, not the cautious hedging of an AI assistant
""".strip()

PROSE_PHILOSOPHY_FOR_CRITIQUE = """
## AI Tell Detection (ALWAYS CHECK)

Flag ANY of these as issues, regardless of style guide:

**Banned Vocabulary** (immediate flags):
- delve, tapestry (metaphorical), myriad, whilst/amidst/amongst
- commence, utilise/utilize, plethora, multifaceted
- paradigm, synergy, leverage (verb), facilitate, encompass
- Sentence starters: furthermore, moreover, additionally

**Structural AI Tells**:
- Everything in threes or perfect parallel structures
- Purple/overwrought prose with excessive adjectives
- Adverb overuse (especially -ly words propping up weak verbs)
- Filter words: "he felt", "she noticed", "he realized"
- Hedging: "somewhat", "rather", "quite" used excessively
- Overly formal or essay-like constructions
- Every conflict resolving too neatly

**Voice Issues**:
- Uniform sentence length throughout
- Lack of fragments or varied rhythm
- Characters all speaking in similar patterns
- Over-explained emotions or motivations
- Cautious, hedging tone instead of confident prose
""".strip()


# Common AI preamble patterns to strip from output
AI_PREAMBLE_PATTERNS = [
    r"^Here'?s?\s+(a\s+)?(the\s+)?(narrative\s+)?(prose\s+)?(draft\s+)?(for\s+)?(scene\s+)?[\d\w\-:]*\s*[:.]?\s*\n*",
    r"^Here\s+is\s+(a\s+)?(the\s+)?(narrative\s+)?(prose\s+)?(draft\s+)?(for\s+)?(scene\s+)?[\d\w\-:]*\s*[:.]?\s*\n*",
    r"^I'?ll\s+write\s+.*?[:.]?\s*\n*",
    r"^Let\s+me\s+write\s+.*?[:.]?\s*\n*",
    r"^This\s+is\s+(a\s+)?(the\s+)?scene.*?[:.]?\s*\n*",
    r"^Scene\s+\d+[:.]?\s*\n*",
    r"^#\s*Scene\s+\d+.*?\n*",
    r"^---+\s*\n*",
]


def clean_prose_output(prose: str) -> str:
    """
    Clean AI-generated prose by removing common preambles and artifacts.

    Args:
        prose: Raw prose output from LLM

    Returns:
        Cleaned prose with preambles stripped
    """
    if not prose:
        return prose

    cleaned = prose.strip()

    # Apply each pattern
    for pattern in AI_PREAMBLE_PATTERNS:
        cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE | re.MULTILINE)

    # Strip any leading/trailing whitespace that resulted from cleanup
    cleaned = cleaned.strip()

    # Remove leading blank lines
    while cleaned.startswith("\n"):
        cleaned = cleaned[1:]

    return cleaned


def build_system_prompt(
    characters: List[Dict[str, Any]],
    world_contexts: List[Dict[str, Any]],
    previous_scene_summaries: List[Dict[str, Any]] = None,
    style_guide: Dict[str, Any] = None,
    references: List[Dict[str, Any]] = None,
    previous_books: List[Dict[str, Any]] = None
) -> str:
    """
    Build system prompt with character, world context, previous scene summaries, style guide,
    reference documents, and previous book summaries for series continuity.

    Args:
        characters: List of character data dictionaries
        world_contexts: List of world context data dictionaries
        previous_scene_summaries: List of previous scene summaries for continuity
        style_guide: Style guide dictionary with pov, tense, tone, heat_level, guide
        references: List of reference documents (style guides, published books, notes)
        previous_books: List of earlier book summaries in series

    Returns:
        Formatted system prompt
    """
    prompt_parts = [
        "You are a skilled novelist writing publishable fiction.",
        "Your prose must be indistinguishable from work by accomplished human authors.",
        "",
        "# BASELINE PROSE STANDARDS",
        "",
        PROSE_PHILOSOPHY,
        ""
    ]

    # Add style guide (authoritative - can extend or override baseline)
    if style_guide:
        prompt_parts.append("\n# PROJECT STYLE GUIDE")
        prompt_parts.append("")
        prompt_parts.append("**The following style guide is AUTHORITATIVE for this project. It may extend or override the baseline standards above.**")
        prompt_parts.append("")

        # Quick reference fields
        if style_guide.get('pov'):
            prompt_parts.append(f"**Point of View:** {style_guide['pov']}")
        if style_guide.get('tense'):
            prompt_parts.append(f"**Tense:** {style_guide['tense']}")
        if style_guide.get('tone'):
            prompt_parts.append(f"**Tone:** {style_guide['tone']}")
        if style_guide.get('heat_level'):
            prompt_parts.append(f"**Heat Level:** {style_guide['heat_level']}")

        # Full guide content
        if style_guide.get('guide'):
            prompt_parts.append("\n## Full Style Guide\n")
            prompt_parts.append(style_guide['guide'])
            prompt_parts.append("")

        prompt_parts.append("")

    # Add previous scene summaries for continuity
    if previous_scene_summaries:
        prompt_parts.append("# STORY SO FAR\n")
        prompt_parts.append("The following scenes have already occurred in this story:\n")
        for i, scene_summary in enumerate(previous_scene_summaries, 1):
            scene_title = scene_summary.get('title', f'Scene {i}')
            summary = scene_summary.get('summary', '')
            prompt_parts.append(f"## {scene_title}\n{summary}\n")
        prompt_parts.append("")

    if characters:
        prompt_parts.append("# CHARACTER INFORMATION\n")
        for char in characters:
            prompt_parts.append(f"## {char.get('metadata', {}).get('name', 'Character')}\n")
            prompt_parts.append(f"**Metadata:**\n{format_metadata(char.get('metadata', {}))}\n")
            prompt_parts.append(f"**Details:**\n{char.get('content', '')}\n")

    if world_contexts:
        prompt_parts.append("\n# WORLD CONTEXT\n")
        for world in world_contexts:
            prompt_parts.append(f"## {world.get('metadata', {}).get('name', 'World')}\n")
            prompt_parts.append(f"**Metadata:**\n{format_metadata(world.get('metadata', {}))}\n")
            prompt_parts.append(f"**Details:**\n{world.get('content', '')}\n")

    # Add reference documents (style references, published books, notes)
    if references:
        prompt_parts.append("\n# REFERENCE DOCUMENTS\n")
        prompt_parts.append("Use these reference documents for style, continuity, and context:\n")

        # Group by type for clarity
        style_refs = [r for r in references if r.get('doc_type') == 'style_reference']
        book_refs = [r for r in references if r.get('doc_type') == 'published_book']
        other_refs = [r for r in references if r.get('doc_type') not in ['style_reference', 'published_book']]

        if style_refs:
            prompt_parts.append("## Style References\n")
            for ref in style_refs:
                prompt_parts.append(f"### {ref.get('title', 'Reference')}\n")
                if ref.get('description'):
                    prompt_parts.append(f"*{ref['description']}*\n")
                content = ref.get('content', '')
                # Truncate very long references to avoid context overflow
                if len(content) > 8000:
                    content = content[:8000] + "\n...[truncated for length]"
                prompt_parts.append(f"{content}\n")

        if book_refs:
            prompt_parts.append("## Published Works Reference\n")
            prompt_parts.append("*Reference these published works for style and continuity:*\n")
            for ref in book_refs:
                prompt_parts.append(f"### {ref.get('title', 'Book')}\n")
                if ref.get('description'):
                    prompt_parts.append(f"*{ref['description']}*\n")
                content = ref.get('content', '')
                if len(content) > 8000:
                    content = content[:8000] + "\n...[truncated for length]"
                prompt_parts.append(f"{content}\n")

        if other_refs:
            prompt_parts.append("## Additional References\n")
            for ref in other_refs:
                prompt_parts.append(f"### {ref.get('title', 'Reference')}\n")
                if ref.get('description'):
                    prompt_parts.append(f"*{ref['description']}*\n")
                content = ref.get('content', '')
                if len(content) > 5000:
                    content = content[:5000] + "\n...[truncated for length]"
                prompt_parts.append(f"{content}\n")

    # Add previous books in series for continuity
    if previous_books:
        prompt_parts.append("\n# EARLIER BOOKS IN SERIES\n")
        prompt_parts.append("This is part of a series. Here are summaries of earlier books for continuity:\n")
        for book in previous_books:
            book_num = book.get('book_number', '?')
            title = book.get('title', 'Untitled')
            prompt_parts.append(f"## Book {book_num}: {title}\n")
            summary = book.get('summary', 'No summary available.')
            prompt_parts.append(f"{summary}\n")
        prompt_parts.append("")

    return "\n".join(prompt_parts)


def build_generation_prompt(scene_outline: Dict[str, Any]) -> str:
    """
    Build prompt for initial prose generation.

    Args:
        scene_outline: Scene data dictionary

    Returns:
        Formatted generation prompt
    """
    parts = [
        "Generate narrative prose for the following scene:",
        "",
        f"# {scene_outline.get('title', 'Untitled Scene')}",
        "",
        f"**Outline:** {scene_outline.get('outline', '')}",
        ""
    ]

    if scene_outline.get('tone'):
        parts.append(f"**Tone:** {scene_outline['tone']}")

    if scene_outline.get('pov'):
        parts.append(f"**Point of View:** {scene_outline['pov']}")

    if scene_outline.get('target_length'):
        parts.append(f"**Target Length:** {scene_outline['target_length']}")

    if scene_outline.get('additional_notes'):
        parts.append(f"\n**Additional Notes:** {scene_outline['additional_notes']}")

    parts.extend([
        "",
        "Write the prose for this scene, incorporating the character and world context provided in the system prompt.",
        "",
        "REMEMBER: Your prose must read as human-written. Follow the baseline prose standards and project style guide.",
        "Avoid all banned vocabulary and AI patterns. Write with the confidence of a published novelist.",
        "",
        "CRITICAL: Output ONLY the prose itself. Do not include:",
        "- Any preamble or introduction (e.g., \"Here's the scene...\", \"Here is the narrative...\")",
        "- Meta-commentary about what you're writing",
        "- Section headers or titles within the prose",
        "- Closing remarks or summaries",
        "",
        "Begin directly with the story content. The first words should be narrative prose."
    ])

    return "\n".join(parts)


def build_critique_prompt(prose: str, style_guide: Dict[str, Any] = None) -> str:
    """
    Build prompt for critiquing generated prose.

    Args:
        prose: The prose text to critique
        style_guide: Optional style guide to critique against

    Returns:
        Formatted critique prompt
    """
    style_section = ""
    if style_guide and style_guide.get('guide'):
        style_section = f"""
# PROJECT STYLE GUIDE
The prose should conform to this style guide (authoritative for this project):

{style_guide.get('guide', '')}

---

"""

    return f"""Please provide a constructive critique of the following prose:

---
{prose}
---

{PROSE_PHILOSOPHY_FOR_CRITIQUE}

{style_section}
Evaluate the prose on these dimensions:

1. **Narrative Flow**: Does the scene progress smoothly and logically?
2. **Character Voice**: Are character voices distinct and authentic?
3. **Sensory Details**: Are there vivid, engaging descriptions without purple prose?
4. **Pacing**: Is the pacing appropriate for the scene's purpose?
5. **Tone**: Does the tone match the intended mood?
6. **Technical Writing**: Are there issues with grammar, repetition, or word choice?
7. **AI Tell Detection**: Flag ANY banned vocabulary or AI patterns from the list above. This is critical.
8. **Style Guide Compliance**: Does the prose follow the project style guide rules?

For each area, provide:
- What works well
- What could be improved
- Specific suggestions for revision

**IMPORTANT**: Be rigorous about AI tells. If you find banned vocabulary (delve, tapestry, myriad, etc.) or structural AI patterns, call them out explicitly with quotes and suggested replacements. The goal is prose indistinguishable from human-written work."""


def build_revision_prompt(original_prose: str, critique: str, user_instructions: str = None) -> str:
    """
    Build prompt for revising prose based on critique.

    Args:
        original_prose: The original prose text
        critique: The critique of the original prose
        user_instructions: Optional additional guidance from the user

    Returns:
        Formatted revision prompt
    """
    # Build the user instructions section if provided
    user_guidance = ""
    if user_instructions and user_instructions.strip():
        user_guidance = f"""
# User Guidance
The author has provided additional direction for this revision:
---
{user_instructions.strip()}
---

Prioritize the author's guidance above general revision suggestions.
"""

    return f"""Please revise the following prose based on the critique provided.

# Original Prose
---
{original_prose}
---

# Critique
---
{critique}
---
{user_guidance}
# Instructions
Revise the prose to address the critique's suggestions while maintaining:
- The core narrative and plot points
- Character consistency
- World building elements

**CRITICAL**: Do not introduce AI tells during revision. Avoid banned vocabulary (delve, tapestry, myriad, whilst, etc.) and AI patterns. Your revision must read as human-written prose.

Focus on improving the specific areas mentioned in the critique. Output only the revised prose, without commentary."""


def build_polish_critique_prompt(prose: str, style_guide: Dict[str, Any] = None) -> str:
    """
    Build prompt for polish-mode critique (line edits, not structural).

    Args:
        prose: The prose text to critique
        style_guide: Optional style guide to critique against

    Returns:
        Formatted polish critique prompt
    """
    style_section = ""
    if style_guide and style_guide.get('guide'):
        style_section = f"""
# STYLE GUIDE REFERENCE
Check for style guide compliance:

{style_guide.get('guide', '')}

---

"""

    return f"""Provide a POLISH critique of the following prose. Focus on LINE-LEVEL refinements, not structural issues.

---
{prose}
---
{style_section}
**POLISH MODE**: This is a light-touch review. Do NOT suggest:
- Restructuring paragraphs or scenes
- Adding or removing major content
- Changing the narrative flow or pacing
- Reorganizing dialogue sequences

Instead, focus ONLY on these polish opportunities:

1. **AI Tell Detection** (PRIORITY): Flag any banned AI vocabulary:
   - delve, tapestry (metaphorical), myriad, whilst/amidst/amongst
   - commence, utilise/utilize, plethora, multifaceted
   - Sentence starters like furthermore, moreover, additionally
   - Hedging words overused: somewhat, rather, quite
2. **Word Choice**: Are there vague words that could be more precise? Overused words? Clichés?
3. **Sentence Rhythm**: Are sentences varied in length? Any awkward constructions?
4. **Redundancy**: Any repeated information or unnecessary words that could be cut?
5. **Clarity**: Any confusing phrases that could be clearer without restructuring?
6. **Sensory Precision**: Could descriptions be sharper with better word choices?
7. **Dialogue Tags**: Any clunky tags or unnecessary adverbs?
8. **Style Guide Compliance**: Minor violations of style rules (not structural ones)

For each issue you find:
- Quote the specific phrase
- Explain why it could be polished (especially if it's an AI tell)
- Suggest a refined alternative

Remember: The goal is refinement, not rewriting. AI tells are the top priority - flag every one."""


def build_polish_revision_prompt(original_prose: str, critique: str, user_instructions: str = None) -> str:
    """
    Build prompt for polish-mode revision (minimal changes, preserve structure).

    Args:
        original_prose: The original prose text
        critique: The polish critique of the original prose
        user_instructions: Optional additional guidance from the user

    Returns:
        Formatted polish revision prompt
    """
    user_guidance = ""
    if user_instructions and user_instructions.strip():
        user_guidance = f"""
# Author's Guidance
{user_instructions.strip()}

Apply the author's specific polish requests.
"""

    return f"""Apply MINIMAL polish edits to the following prose based on the critique.

# Original Prose
---
{original_prose}
---

# Polish Critique
---
{critique}
---
{user_guidance}
# POLISH MODE INSTRUCTIONS

**Make the smallest changes possible.** This is NOT a rewrite.

DO:
- Replace any AI tell vocabulary (delve, tapestry, myriad, whilst, etc.) with natural alternatives
- Swap individual words for more precise alternatives
- Tighten wordy phrases
- Fix awkward sentence constructions
- Remove unnecessary adverbs or redundant words
- Improve word variety where flagged

DO NOT:
- Restructure paragraphs
- Add or remove sentences
- Change the order of events or dialogue
- Expand descriptions significantly
- Alter the narrative flow
- Introduce new AI tells while fixing others

Your revision should be nearly identical to the original, with surgical word-level improvements. The result must read as human-written.

Output only the polished prose, without commentary."""


def build_selection_revision_prompt(
    full_prose: str,
    selection: str,
    selection_start: int,
    selection_end: int,
    critique: str = None,
    user_instructions: str = None
) -> str:
    """
    Build prompt for revising only a selected portion of prose.

    Args:
        full_prose: The complete prose text
        selection: The selected text to revise
        selection_start: Start index of selection
        selection_end: End index of selection
        critique: Optional critique context
        user_instructions: Optional user guidance for revision

    Returns:
        Formatted selection revision prompt
    """
    # Get context around the selection (1-2 paragraphs before and after)
    before_text = full_prose[:selection_start]
    after_text = full_prose[selection_end:]

    # Find paragraph boundaries for context
    para_before = before_text.rfind('\n\n')
    context_before = before_text[para_before+2:] if para_before != -1 else before_text[-500:]

    para_after = after_text.find('\n\n')
    context_after = after_text[:para_after] if para_after != -1 else after_text[:500]

    # Build critique section if provided
    critique_section = ""
    if critique:
        critique_section = f"""
# Relevant Critique
The AI critique of the full scene included:
---
{critique}
---
Consider these points when revising the selection.
"""

    # Build user instructions section if provided
    user_guidance = ""
    if user_instructions and user_instructions.strip():
        user_guidance = f"""
# Author's Guidance
{user_instructions.strip()}

Prioritize the author's specific instructions for this revision.
"""

    return f"""Revise ONLY the selected portion of prose below. Keep the surrounding context in mind for flow and consistency.

# Context Before Selection
---
...{context_before}
---

# SELECTED TEXT TO REVISE
---
{selection}
---

# Context After Selection
---
{context_after}...
---
{critique_section}{user_guidance}
# Instructions
Rewrite ONLY the selected text. Your output should:
1. Flow naturally from the context before
2. Lead smoothly into the context after
3. Maintain the same POV, tense, and narrative voice
4. Be approximately the same length (unless instructed otherwise)
5. **Avoid AI tells**: No banned vocabulary (delve, tapestry, myriad, whilst, etc.) or AI patterns

Your revision must read as human-written prose. Output ONLY the revised selection text, nothing else. Do not include the surrounding context."""


def build_summary_prompt(scene_title: str, prose: str) -> str:
    """
    Build prompt for generating a scene summary.

    Args:
        scene_title: Title of the scene
        prose: The final prose text to summarize

    Returns:
        Formatted summary generation prompt
    """
    return f"""Generate a concise summary of the following scene for continuity tracking.

# Scene: {scene_title}

# Prose:
---
{prose}
---

# Instructions:
Create a summary (300-500 words) that captures:

1. **Key Events**: What happened in this scene? What plot points were advanced?
2. **Character Development**: How did characters change or reveal themselves?
3. **Emotional Beats**: What were the key emotional moments?
4. **World State Changes**: Did anything change in the world or setting?
5. **Open Threads**: What questions or conflicts were raised but not resolved?
6. **Continuity Details**: Specific facts, locations, or objects that future scenes should remember

Write the summary in past tense, as if you're documenting what already happened. Be specific about names, places, and key details that maintain continuity.

Output only the summary, without commentary or section headers."""


def format_metadata(metadata: Dict[str, Any]) -> str:
    """
    Format metadata dictionary as readable text.

    Args:
        metadata: Metadata dictionary

    Returns:
        Formatted string
    """
    lines = []
    for key, value in metadata.items():
        if isinstance(value, list):
            lines.append(f"- **{key}**: {', '.join(str(v) for v in value)}")
        elif isinstance(value, dict):
            lines.append(f"- **{key}**:")
            for sub_key, sub_value in value.items():
                lines.append(f"  - {sub_key}: {sub_value}")
        else:
            lines.append(f"- **{key}**: {value}")
    return "\n".join(lines)
